# Use Python as the base image
FROM python:3.14-slim

# Set the working directory
WORKDIR /app

# Copy the Python program into the container
COPY Vinil_module7_5.py .

# Run the Python program
CMD ["python", "Vinil_module7_5.py"]

