
FROM python:3.14-slim

# Set the working directory
WORKDIR /app

# Create the data folder
RUN mkdir -p /app/data

# Copy the Python program
COPY Vinil_module7_4.py .

# Run the Python program
CMD ["python", "Vinil_module7_4.py"]

