# Use Python as the base image
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Copy the Python program into the container
COPY Vinil_module7_1.py .

# Run the Python program
CMD ["python", "Vinil_module7_1.py"]