import sqlite3

# Database file
DATABASE = "users_main.db"


def create_database():
    """Create the users table if it does not exist."""

    connection = sqlite3.connect(DATABASE)
    cursor = connection.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            age INTEGER,
            city TEXT
        )
    """)

    connection.commit()
    connection.close()


def add_user(name, age, city):
    """Add a new user to the database."""

    connection = sqlite3.connect(DATABASE)
    cursor = connection.cursor()

    cursor.execute(
        """
        INSERT INTO users (name, age, city)
        VALUES (?, ?, ?)
        """,
        (name, age, city)
    )

    connection.commit()

    # Get the ID generated by SQLite
    user_id = cursor.lastrowid

    connection.close()

    return {
        "id": user_id,
        "name": name,
        "age": age,
        "city": city
    }


def get_all_users():
    """Return all users from the database."""

    connection = sqlite3.connect(DATABASE)
    cursor = connection.cursor()

    cursor.execute(
        "SELECT id, name, age, city FROM users"
    )

    rows = cursor.fetchall()

    connection.close()

    users = []

    for row in rows:
        users.append({
            "id": row[0],
            "name": row[1],
            "age": row[2],
            "city": row[3]
        })

    return users


def search_users(name):
    """Search users by name."""

    connection = sqlite3.connect(DATABASE)
    cursor = connection.cursor()

    cursor.execute(
        """
        SELECT id, name, age, city
        FROM users
        WHERE name LIKE ?
        """,
        (f"%{name}%",)
    )

    rows = cursor.fetchall()

    connection.close()

    users = []

    for row in rows:
        users.append({
            "id": row[0],
            "name": row[1],
            "age": row[2],
            "city": row[3]
        })

    return users


# Create the database when this file is used
create_database()